import mongoose from 'mongoose';
import dotenv from 'dotenv';
import { fileURLToPath } from 'url';
import path from 'path';
import User from '../src/models/user.model.js';
import Organization from '../src/models/organization.model.js';
import { generateRandomPassword } from '../src/utils/helpers.js';

// Load environment variables
dotenv.config();

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Connect to MongoDB
const connectDB = async () => {
  try {
    await mongoose.connect('mongodb://localhost:27017/charity_platform', {
      useNewUrlParser: true,
      useUnifiedTopology: true,
    });
    console.log('MongoDB Connected...');
  } catch (err) {
    console.error('MongoDB connection error:', err);
    process.exit(1);
  }
};

const fixOrganizationUsers = async () => {
  try {
    console.log('Starting to fix organization users...');
    
    // Find all approved organizations
    const organizations = await Organization.find({ status: 'approved' });
    console.log(`Found ${organizations.length} approved organizations`);
    
    let fixedCount = 0;
    const errors = [];
    
    // Process each organization
    for (const org of organizations) {
      try {
        // Check if organization has a linked user
        if (!org.user) {
          console.log(`\nProcessing organization: ${org.organizationName} (${org._id})`);
          console.log('No linked user found, creating one...');
          
          // Check if a user with this email already exists
          let user = await User.findOne({ email: org.officialEmail });
          
          if (user) {
            // User exists, link to organization
            console.log(`Found existing user: ${user.email} (${user._id})`);
            org.user = user._id;
            user.role = 'organization';
            user.organization = org._id; // Fix bidirectional link
            user.isVerified = true;
            await user.save();
          } else {
            // Create new user
            const password = generateRandomPassword(12);
            user = new User({
              name: org.representativeName,
              email: org.officialEmail,
              password: password,
              role: 'organization',
              organization: org._id, // Fix bidirectional link
              isVerified: true,
              isPasswordAutogenerated: true
            });
            
            await user.save();
            console.log(`Created new user: ${user.email} (${user._id})`);
            
            // Link user to organization
            org.user = user._id;
          }
          
          // Save organization with linked user
          await org.save();
          
          console.log(`Successfully linked user ${user._id} to organization ${org._id}`);
          fixedCount++;
        } else {
          console.log(`\nOrganization ${org.organizationName} (${org._id}) already has a linked user: ${org.user}`);
          
          // Verify the linked user exists
          const user = await User.findById(org.user);
          if (!user) {
            console.error(`ERROR: Linked user ${org.user} not found for organization ${org._id}`);
            errors.push({
              organizationId: org._id,
              error: `Linked user ${org.user} not found`
            });
          } else {
            // Ensure bidirectional link exists even if user exists
             if (!user.organization || user.organization.toString() !== org._id.toString()) {
                console.log(`Fixing missing bidirectional link for user: ${user._id}`);
                user.organization = org._id;
                await user.save();
                fixedCount++;
             } else {
                console.log(`Verified bidirectional link for user: ${user.email} (${user._id})`);
             }
          }
        }
      } catch (error) {
        console.error(`Error processing organization ${org._id}:`, error);
        errors.push({
          organizationId: org._id,
          error: error.message
        });
      }
    }
    
    console.log('\n--- Fix Complete ---');
    console.log(`Organizations processed: ${organizations.length}`);
    console.log(`Users fixed/created: ${fixedCount}`);
    
    if (errors.length > 0) {
      console.log('\n--- Errors ---');
      console.log(JSON.stringify(errors, null, 2));
    }
    
    process.exit(0);
  } catch (error) {
    console.error('Fatal error in fixOrganizationUsers:', error);
    process.exit(1);
  }
};

// Run the script
(async () => {
  await connectDB();
  await fixOrganizationUsers();
})();
